### ISSUE TITLE
getting loss as NAN during training for 7k crops and their respective gt

### ISSUE THREAD

**Issue by anidiatm41** [AryanSh98/crnn-pytorch#3]
\ptr_torch4>python train.py
device: cpu
epoch: 1
 54%|█████████████████████████████████████████████████████████████████▊                                                       | 31/57 [12:31<07:45, 17.90s/batch, loss=nan]Corrupted image for 2019
 56%|███████████████████████████████████████████████████████████████████▉                                                     | 32/57 [12:44<09:56, 23.88s/batch, loss=nan]

**Comment by arxyzan** [comment]
There are a couple of reasons why this might happen:
1. You are including `blank` character in your dataset meaning that a character in your dataset is labeled as the blank character in `nn.CTCLoss()` which by default is `0`.  
2. You are including `" " (space)` character. I faced this issue too. I had to remove all spaces from the texts.
To clear things out can you paste your Dataset class here?

**Comment by anidiatm41** [comment]
Thanks for your quick response, I do have blank in my labels and as a result I have space in my characters too.

Below my labels are:

7,35,00,00,003.00
3,05,75,34.46Cr
256
Page 1 of 1
Total Debit :
257
45,00,30,000.00
Total Credit :
255
0.00 % p.a.
ABC BANK
0
02/06/2020 to 07/07/2020
C BALANCE
8,05,75,824.86Cr
60,00,70,000.00
5,75,834.46Cr
Time : 11:42:23
Account No. :700000592

**Comment by arxyzan** [comment]
This is how it works when instantiating a dataset:
There should be a string of your alphabet like so: 
```python
alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890!@#$%^&*()-_=+/|\<>?"
```
Then 2 dictionaries of their mappings are created : `CHAR2LABEL`: Each and every character in the given alphabet as key and a number as the value and `LABEL2CHAR` which is the same dictionary with the key value pairs reversed:
```python
CHAR2LABEL = {'A': 1, 'B': 2, ...}
LABEL2CHAR = {1: 'A', 2: 'B', ...}
```
As you can see we don't include `space` in the alphabet neither the label `0` in labels. (labels start from 1). I'm not really sure if including `space` in the alphabet would break things up or not but it surely is an essential character in your dataset (in most cases you have a text detector e.g. CRAFT, which can detect every piece of word or symbol so that there is no need for recognizing spaces)
